Piza_Analytics:
  outputs:
    dev:
      type: duckdb
      path: D:\Projects\PizaSalesAnalysis\pizza.duckdb
      threads: 1

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
